export const CATEGORIES = ['All', 'Indoor Plants', 'Outdoor Plants', 'Succulents', 'Seeds', 'Pots & Planters', 'Tools', 'Fertilizers']

export const MOCK_PRODUCTS = [
  {
    id: 1,
    name: 'Monstera Deliciosa',
    price: 649,
    category: 'Indoor Plants',
    image: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=500&auto=format',
    description: 'The iconic Swiss cheese plant, perfect for bright indirect light. A statement piece for any room.',
    rating: 4.8,
    reviews: 234,
    in_stock: true,
    badge: 'Bestseller',
  },
  {
    id: 2,
    name: 'Peace Lily',
    price: 349,
    category: 'Indoor Plants',
    image: 'https://images.unsplash.com/photo-1593691509543-c55fb32d8de5?w=500&auto=format',
    description: 'Elegant white blooms and air-purifying properties. Thrives in low light conditions.',
    rating: 4.7,
    reviews: 189,
    in_stock: true,
    badge: 'Air Purifier',
  },
  {
    id: 3,
    name: 'Echeveria Set of 3',
    price: 299,
    category: 'Succulents',
    image: 'https://images.unsplash.com/photo-1509423350716-97f9360b4e09?w=500&auto=format',
    description: 'Beautiful rosette-forming succulents in assorted colors. Nearly indestructible!',
    rating: 4.9,
    reviews: 312,
    in_stock: true,
    badge: 'Low Maintenance',
  },
  {
    id: 4,
    name: 'Rose Bush — Pink Queen',
    price: 499,
    category: 'Outdoor Plants',
    image: 'https://images.unsplash.com/photo-1548460456-1f5c57dac7b3?w=500&auto=format',
    description: 'Classic pink rose bush with abundant blooms. Perfect for garden borders.',
    rating: 4.6,
    reviews: 156,
    in_stock: true,
    badge: null,
  },
  {
    id: 5,
    name: 'Ceramic Terracotta Pot',
    price: 199,
    category: 'Pots & Planters',
    image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=500&auto=format',
    description: 'Handcrafted terracotta pot with drainage hole. Ideal for most houseplants.',
    rating: 4.5,
    reviews: 98,
    in_stock: true,
    badge: 'Handmade',
  },
  {
    id: 6,
    name: 'Marigold Seeds Pack',
    price: 49,
    category: 'Seeds',
    image: 'https://images.unsplash.com/photo-1490750967868-88df5691cc9a?w=500&auto=format',
    description: 'Premium marigold seeds — 200+ seeds per pack. Easy to grow, pest-repelling.',
    rating: 4.8,
    reviews: 445,
    in_stock: true,
    badge: 'Value Pack',
  },
  {
    id: 7,
    name: 'Fiddle Leaf Fig',
    price: 899,
    category: 'Indoor Plants',
    image: 'https://images.unsplash.com/photo-1517191434949-5e90cd67d2b6?w=500&auto=format',
    description: 'Dramatic large leaves make this a stunning focal point. Loves bright indirect light.',
    rating: 4.4,
    reviews: 127,
    in_stock: true,
    badge: 'Premium',
  },
  {
    id: 8,
    name: 'Organic Fertilizer Mix',
    price: 189,
    category: 'Fertilizers',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=500&auto=format',
    description: '100% organic slow-release fertilizer. Safe for all plants and family-friendly.',
    rating: 4.7,
    reviews: 203,
    in_stock: true,
    badge: 'Organic',
  },
  {
    id: 9,
    name: 'Snake Plant',
    price: 399,
    category: 'Indoor Plants',
    image: 'https://images.unsplash.com/photo-1597305877032-0668b3c6413a?w=500&auto=format',
    description: 'Nearly indestructible, purifies air at night. Perfect for beginners.',
    rating: 4.9,
    reviews: 567,
    in_stock: true,
    badge: 'Beginner Friendly',
  },
  {
    id: 10,
    name: 'Garden Tool Kit',
    price: 549,
    category: 'Tools',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=500&auto=format',
    description: 'Complete 5-piece stainless steel tool set with ergonomic handles.',
    rating: 4.6,
    reviews: 89,
    in_stock: true,
    badge: 'Kit',
  },
  {
    id: 11,
    name: 'String of Pearls',
    price: 279,
    category: 'Succulents',
    image: 'https://images.unsplash.com/photo-1520302630591-fd1e4563b0f1?w=500&auto=format',
    description: 'Cascading bead-like leaves create a stunning trailing effect. Great for hanging pots.',
    rating: 4.7,
    reviews: 178,
    in_stock: true,
    badge: null,
  },
  {
    id: 12,
    name: 'Bamboo Hanging Planter',
    price: 329,
    category: 'Pots & Planters',
    image: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=500&auto=format',
    description: 'Eco-friendly bamboo hanging planter set of 2. Adds a boho touch to any space.',
    rating: 4.5,
    reviews: 134,
    in_stock: true,
    badge: 'Eco-Friendly',
  },
]
